name: Deploy React CSR
on:
  push:
  # ทำงานตามเงื่อนไขeventที่เกิดขึ้น
    branches:
      - main
      - feature/**
  workflow_dispatch:
  pull_request:
    types:
      - opened
#env:
 # BUN_VERSION: "1.2.18"

jobs:
  build:
    environment: productionBest
    runs-on: ubuntu-latest
    steps:
      - name: Print Bun version
        run: echo "Bun version:${{ vars.BUN_VERSION}}"
      - name: Print API key
        run: echo "API key:${{ secrets.API_KEY }}"
      - name: Clone repo
        uses: actions/checkout@v5
      - name: Caching
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install deps
        run: npm install
      - name: Build
        run: npm run build
      - name: List dist/
        run: ls dist
      - name: Upload dist/
        uses: actions/upload-artifact@v4
        with:
          name: dist-floder
          path: dist/
      - name: Force failed
        run: exit 1

  deploy:
    if: success()
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download dist
        uses: actions/download-artifact@v4
        with:
          name: dist-floder
          path: dist
      - name: Deploy
        run: echo "Deploying..."

  notify:
    runs-on: ubuntu-latest
    needs:
      - build
      - deploy
    if: failure()
    steps: 
      - name: discord notification
        env:
          DISCORD_WEBHOOK: https://discord.com/api/webhooks/1421697869458706533/W2UqZa7gD95EU7ixa4gQN3QLz3pWc3oFepvpv16XWxfpuMMTTiqbNULZWrBBmPfPlYBY
        uses: Ilshidur/action-discord@master
        with:
          args: 'Build failed by Best!'